spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gone9227/spring-cloud-config.git
#          searchPaths: config
          searchPaths:
            - "config/{application}"
            - "."

server:
  port: 8888